# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 10:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_date', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='published_on',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='loan',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='librarian.Book'),
        ),
        migrations.AddField(
            model_name='loan',
            name='patron',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='librarian.Patron'),
        ),
    ]
